# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75d306557723a3037d26135c3d2467f0d25f77a71c7119a96740873be4372c77ca71485340665a4f10279d2d551d619b8f7a58b2d8a4753acf3d2326f869fd24

test:
  secret_key_base: bc36c14280b96297c4a3f36ab1243dea0d0bfe4b76d3c2a5e6fbb69ea576b47cd0c2a1edab3c924591b0d29fde388bae81011b60750e6c3fe2fddc555bd7f694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
